package ba.unsa.etf.rpr.business;

import ba.unsa.etf.rpr.dao.DaoFactory;
import ba.unsa.etf.rpr.domain.Appointments;
import ba.unsa.etf.rpr.exceptions.HairsalonException;

import java.util.List;

public class AppointmentsManager {
    public Appointments add(Appointments a) throws HairsalonException {
        if (a.getId() != 0) {
            throw new HairsalonException("Can't add Appointments with ID. ID is autogenerated");
        }
        return DaoFactory.appointmentsDao().add(a);
    }

    public void delete(int id) throws HairsalonException {
        DaoFactory.appointmentsDao().delete(id);
    }

    public void update(Appointments a) throws HairsalonException {
        DaoFactory.appointmentsDao().update(a);
    }

    public List<Appointments> getAll() throws HairsalonException {
        return DaoFactory.appointmentsDao().getAll();
    }
    public Appointments getById(int AppointmentsId) throws HairsalonException {
        return DaoFactory.appointmentsDao().getById(AppointmentsId);
    }
}
