package ba.unsa.etf.rpr.business;

import ba.unsa.etf.rpr.dao.Dao;
import ba.unsa.etf.rpr.dao.DaoFactory;
import ba.unsa.etf.rpr.domain.Stylist;
import ba.unsa.etf.rpr.exceptions.HairsalonException;

import java.util.List;

public class StylistManager {

    public Stylist add(Stylist s) throws HairsalonException {
        if (s.getId() != 0) {
            throw new HairsalonException("Can't add Stylist with ID. ID is autogenerated");
        }
        return DaoFactory.stylistDao().add(s);
    }

    public void delete(int id) throws HairsalonException {
        DaoFactory.stylistDao().delete(id);
    }

    public void update(Stylist s) throws HairsalonException {
        DaoFactory.stylistDao().update(s);
    }

    public List<Stylist> getAll() throws HairsalonException {
        return DaoFactory.stylistDao().getAll();
    }
    public Stylist getById(int stylistId) throws HairsalonException{
        return DaoFactory.stylistDao().getById(stylistId);
    }
}
