package ba.unsa.etf.rpr.business;

import ba.unsa.etf.rpr.dao.DaoFactory;
import ba.unsa.etf.rpr.domain.User;
import ba.unsa.etf.rpr.exceptions.HairsalonException;

import java.util.List;

public class UserManager {

    public void validateUserName(String name) throws HairsalonException {
        if (name == null || name.length() > 45 || name.length() < 3) {
            throw new HairsalonException("User name must be between 6 and 15 chars");
        }
    }

    public User add(User u) throws HairsalonException {
        if (u.getId() != 0) {
            throw new HairsalonException("Can't add User with ID. ID is autogenerated");
        }
        validateUserName(u.getUsername());

        try {
            return DaoFactory.userDao().add(u);
        } catch (HairsalonException e) {
            if (e.getMessage().contains("UQ_NAME")) {
                throw new HairsalonException("User with same username exists");
            }
            throw e;
        }
    }

    public void delete(int UserId) throws HairsalonException {
        try {
            DaoFactory.userDao().delete(UserId);
        } catch (HairsalonException e) {
            if (e.getMessage().contains("FOREIGN KEY")) {
                throw new HairsalonException("Cannot delete User which is related to appointments. First delete related appointments before deleting User.");
            }
            throw e;
        }

    }

    public User update(User u) throws HairsalonException {
        validateUserName(u.getUsername());
        return DaoFactory.userDao().update(u);
    }

    public List<User> getAll() throws HairsalonException {
        return DaoFactory.userDao().getAll();
    }
    public User getById(int userId) throws HairsalonException{
        return DaoFactory.userDao().getById(userId);
    }
}
